version: "3.9"

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    environment:
      # std4453:std4453
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./jackett:/config
    networks:
      - public
    # expose: 9117
    extra_hosts:
      - host:host-gateway # access host socks5 proxy
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
    networks:
      - public
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:preview # Sonarr v3
    container_name: sonarr
    hostname: sonarr
    environment:
      # std4453:std4453
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    networks:
      - public
    # expose: 8989
    volumes:
      - ./sonarr:/config
      - ./downloads:/downloads
      - ./media:/media
    extra_hosts:
      - host:host-gateway # access host socks5 proxy
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    networks:
      - public
    # expose: 676
    volumes:
      - ./bazarr:/config
      - ./downloads:/downloads
      - ./media:/media
    extra_hosts:
      - host:host-gateway # access host socks5 proxy
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      # std4453:std4453
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/combustion-release/
    networks:
      - public
    ports:
      - 8080:8080
      # required for bittorrent connections
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
      - ./media:/media
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:10.7.0-rc3
    container_name: jellyfin
    hostname: jellyfin
    user: 1000:1000 # std4453:std4453
    group_add:
      - 989 # render, unnecessary perhaps
    networks:
      - public
    # expose: 8096
    volumes:
      - ./jellyfin/web-config.json:/jellyfin/jellyfin-web/config.json
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./media:/media
      - ./jellyfin/fonts:/fonts
    devices:
      - /dev/dri:/dev/dri # HW Accel, although not enabled currently
    restart: unless-stopped

networks:
  public:
    external: true
